### ISSUE TITLE
Solution for Partitioning Into Minimum Number Of Deci-Binary Numbers

### ISSUE THREAD

**Issue by Keerat666** [Keerat666/LeetCode-HacktoberFest22#4]
Write a program to solve Partitioning Into Minimum Number Of Deci-Binary Numbers.

Link : https://leetcode.com/problems/partitioning-into-minimum-number-of-deci-binary-numbers/

**Comment by AlphaVS-76** [comment]
Can i get assigned this issue

**Comment by sakshi135** [comment]
please assign me this issue.
